### PR TITLE
Add rpath

### PR DESCRIPTION
**Pull request by bjoo**
Hi Frank, 
 I have added a couple of minor mods here, to 
 a) add -Wl,-rpath,[LLVM_LIBDIR]

to the link line. This way one doesn't need to worry about having LLVM on $LD_LIBRARY_PATH as
the link path is in  the executable

b) Minor tweaks to suppress some warnings. Worth reviewing ones in qdp_llvm.cc where I have
replaced the pattern of :

Original:

 llvm::Type* args_type = vals.first->getType();
 assert( !args_type->isFloatingPointTy() );

with 

  assert( ! ( vals.first->getType()->isFloatingPointTy() ) );

When NDEBUG is enabled (Release versions of LLVM I guess) the original pattern no longer
referenes args_type as the assert is removed fro the code and an unuse variable warning is generated. 
The second version collapses the two lines of the first into single assert.

The rest of the stuff was in the qdp_qdpio.cc and qdp_qio_strings.cc mostly just type casting
to silence warnings.

Best, B

### CODE REVIEW

**Comment by bjoo** [comment]
Ugh. Now some follow up chroma code has an issue. I will close this pull req for now but can reopen it later when I put in the downstream fixes. Apologies.

**Comment by bjoo** [comment]
OK. There were a few auxiliary const_cast-s needed. Chroma now builds with the most recent commit on this branch.

**Comment by bjoo** [comment]
Merged in llvm-nvptx-subtype branch which has since developed. NB:  Module::dump() seemed to not be there in my Release build of LLVM-6.0.0 causing unresolved symbols on linking. Compiling LLVM in Debug mode fixed these.

**Comment by fwinter** [comment]
Hey Balint! Please use the debug build of LLVM. This gets the most testing and also doesn't affect the generated code. Only compilation time is longer.

**Comment by bjoo** [comment]
Will do! I learned it the hard way :)
Thanks! 
 Balint


> On Jul 13, 2018, at 2:43 PM, Frank Winter <notifications@github.com> wrote:
> 
> Hey Balint! Please use the debug build of LLVM. This gets the most testing and also doesn't affect the generated code. Only compilation time is longer.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-----------------------------------------------------------------------------
Dr Balint Joo   High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave Suite 3, MS 12B2, Room F217
Newport News VA 23606, USA
Tel: +1-757-269-5339         email: bjoo AT jlab.org
-----------------------------------------------------------------------------

**Pull request merged**
